#!MANAGED-CONFIG https://raw.zhai.dev/bottomash/sub/latest/surge/policy.conf

[Proxy Group]
AGI = fallback, include-all-proxies=true, policy-regex-filter="^(?=.*(?:(美国|韩国|日本|新加坡)))(?!.*(?:3[xX]|5[xX]|10[xX]|家宽|星链|住宅|游戏)).*$", url=https://www.gstatic.com/generate_204, interval=300
Auto = fallback, PROXY, include-all-proxies=true, policy-regex-filter="^(?=.*(?:(日本|香港|新加坡|韩国|土耳其)))(?!.*(?:3[xX]|5[xX]|10[xX]|家宽|星链|住宅|游戏)).*$", url=https://www.gstatic.com/generate_204, interval=300
PROXY = select, include-all-proxies=true, policy-regex-filter="^(?=.*(?:(日本|香港|新加坡|韩国|土耳其)))(?!.*(?:3[xX]|5[xX]|10[xX]|家宽|星链|住宅|游戏|台湾)).*$"
OneDrive = select, DIRECT, Auto

[Rule]
RULE-SET,https://raw.zhai.dev/bottomash/sub/latest/rule/agi.txt,AGI
RULE-SET,https://raw.zhai.dev/bottomash/sub/latest/rule/onedrive.txt,OneDrive
RULE-SET,https://raw.zhai.dev/bottomash/sub/latest/rule/direct.txt,DIRECT
RULE-SET,https://raw.zhai.dev/bottomash/sub/latest/rule/proxy.txt,Auto
RULE-SET,LAN,DIRECT
GEOIP,CN,DIRECT
FINAL,Auto
